services:
  - type: web
    name: snippets
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: snippets-db
          property: connectionString

databases:
  - name: snippets-db
    plan: free
    ipAllowList: [] 